### ISSUE TITLE
Camera will clip through objects with added offset

### ISSUE THREAD

**Issue by DeshiDesu** [LugicalDev/CameraService#2]
Camera will start clipping through objects if added negative y offset.

The line of code in question:
https://github.com/LugicalDev/CameraService/blob/61b2546005a0e866b7d1f5bd1406ffc9898279d9/CameraService.lua#L234

I fixed this by manually adding an offset, although not recommended.
```lua
	local rayOffset = Vector3.new(0, -1, 0)
	local landRay = workspace:Raycast((currentCamPosition + rayOffset), (rotationCFrame * Vector3.new(0, 0, currentZoom)), params)
```

**Comment by LugicalDev** [comment]
Thanks for the report! I've just committed a solution for this, using the Offset property in CameraService. Thanks again.
